
include:
  - board: akdk_bt1
    shield: moder63
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artificial-name: moder63
  - board: akdk_bt1
    shield: settings_reset
    artificial-name: settings_reset-akdk_bt1-zmk
